# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # npm projects
  - package-ecosystem: "npm"
    directory: "/Lab0"
    schedule:
      interval: "weekly"
      day: 'friday'
      time: '09:00'
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
  
  - package-ecosystem: "npm"
    directory: "/Lab4"
    schedule:
      interval: "weekly"
      day: 'friday'
      time: '09:00'
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
  
  - package-ecosystem: "npm"
    directory: "/hw3"
    schedule:
      interval: "weekly"
      day: 'friday'
      time: '09:00'
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
  
  - package-ecosystem: "npm"
    directory: "/hw4"
    schedule:
      interval: "weekly"
      day: 'friday'
      time: '09:00'
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
  
  # Go project
  - package-ecosystem: "gomod"
    directory: "/hw2"
    schedule:
      interval: "weekly"
      day: 'friday'
      time: '09:00'
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
